assignmentOne: Main.o rr.o fcfs.o sjf.o
	gcc -o runAssignmentOne Main.o rr.o fcfs.o sjf.o

Main.o: Main.c Main.h
	gcc -c Main.c 

rr.o: rr.c rr.h
	gcc -c rr.c

fcfs.o: fcfs.c fcfs.h
	gcc -c fcfs.c

sjf.o: sjf.c sjf.h
	gcc -c sjf.c